import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { TiTick, TiTimes } from "react-icons/ti";

export default function Home({ data }) {
  const [val, setVal] = useState([]);
  const [num, setNum] = useState(2);

  useEffect(() => {
    setVal(data.data);
  }, []);

  const requestNextPage = async () => {
    if (num == 0) {
      setNum(num + 1);
      const res = await fetch(
        `https://gorest.co.in/public/v1/users?page=${num}`
      );
      const data = await res.json();
      setVal(data.data);
    } else {
      const res = await fetch(
        `https://gorest.co.in/public/v1/users?page=${num}`
      );
      const data = await res.json();
      setVal(data.data);
      setNum(num + 1);
    }
  };

  const requestPreviousPage = async () => {
    if (num == 0) {
    } else {
      const res = await fetch(
        `https://gorest.co.in/public/v1/users?page=${num}`
      );
      const data = await res.json();
      setVal(data.data);
      setNum(num - 1);
    }
  };

  return (
    <div>
      <Head>
        <title>USER MANAGEMENT SYSTEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="my-5">
        <div className="container">
          <table className="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">E-Mail</th>
                <th scope="col">Gender</th>
                <th scope="col">Status</th>
                <th scope="col">Detail</th>
              </tr>
            </thead>
            <tbody>
              {val.map((user) => (
                <tr key={user.id}>
                  <th scope="row">{user.id}</th>
                  <td>{user.name}</td>
                  <td>{user.email}</td>
                  <td>{user.gender}</td>
                  <td>{user.status}</td>
                  <td>
                    <Link href={`/User/${user.id}`}>
                      <a className="btn btn-primary">Details</a>
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <button
            className="btn btn-info float-start mb-3"
            onClick={() => requestPreviousPage()}
          >
            Previous
          </button>
          <button
            className="btn btn-danger float-end mb-3"
            onClick={() => requestNextPage()}
          >
            Next
          </button>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://gorest.co.in/public/v1/users");
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}
